POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "name": "pepito",
    "email": "pepito@gmail.com",
    "birthday": "1997-03-02",
    "gender": "otro",
    "career": "ingenieria de sistemas",
    "password": "laurent"
}